HW: Download Contacts from Contacts Provider
s9myon/android_course pull request #5
Opened 2021-12-09 11:40 UTC by s9myon

1. Changed functions getContactList and getContactById from ContactService (They can now download contacts from the ContactProvider.).
2. Added functions getContactBirthdayFromContentProvider, getContactEmailsFromContentProvider, getContactPhoneNumbersFromContentProvider into ContactService
3. Overrided function onRequestPermissionsResult from MainActivity and added the ability to add permissions manually
4. Added permissions for reading of contacts to AndroidManifest
5. Added a few changes to the view of ContactDetailsFragment

2021-12-12 15:13 UTC, nmodelov commented
1. Добавлять скриншоты экранов
2. ставь на ревью только меня, чтобы других не беспокоить уведомлениями
3. Добавлять в описание задание с домашки

2021-12-12 15:44 UTC, nmodelov requested changes

2021-12-12 15:44 UTC, nmodelov commented on app/src/main/java/com/shudss00/android_course/Contact.kt
> +    override fun toString(): String {
у data class и так определен toString под капотом, это можно не делать.

2021-12-12 15:44 UTC, nmodelov commented on app/src/main/java/com/shudss00/android_course/Contact.kt
> +    val dayOfBirth: Calendar? = null
для чего тебе эти статичные поля?

2021-12-12 15:44 UTC, nmodelov commented on app/src/main/java/com/shudss00/android_course/ContactDetailsFragment.kt
> +                    buttonBirthdayNotify.visibility = View.INVISIBLE
вместо View.visibility используй:
View.isVisible или View.isInvisible

2021-12-12 15:44 UTC, nmodelov commented on app/src/main/java/com/shudss00/android_course/ContactService.kt
> +                                null,
Скобочки потерялись.
```
 if (numberList != null && numberList.isNotEmpty()) {
                                numberList[0]
}  else {
  null
}
```

2021-12-12 15:44 UTC, nmodelov commented on app/src/main/java/com/shudss00/android_course/MainActivity.kt
> +            Toast.makeText(this, "Требуется установить разрешения", Toast.LENGTH_LONG).show()
"Требуется установить разрешения"  в ресурсы

2021-12-12 15:44 UTC, nmodelov commented on app/src/main/java/com/shudss00/android_course/MainActivity.kt
>                  .putExtra(MESSAGE, "Today is ${contact.name}'s birthday")
строку в ресурсы

2021-12-12 15:44 UTC, nmodelov commented on app/src/main/java/com/shudss00/android_course/ContactService.kt
> +                            number = if (numberList.isNotEmpty()) numberList[0] else null
Пожалуйста, не пропускай скобочки.
пиши так:
```
if (условие) {
что-то
} else {
что-то
}
```

2021-12-12 15:44 UTC, nmodelov commented on app/src/main/java/com/shudss00/android_course/ContactService.kt
> +                    var birthday: Calendar?
с этим что-то можно сделать?

2021-12-12 15:44 UTC, nmodelov commented on app/src/main/java/com/shudss00/android_course/ContactService.kt
> +                    var contact: Contact?
С этим что-то можно сделать?

2021-12-12 15:44 UTC, nmodelov commented on app/src/main/java/com/shudss00/android_course/ContactService.kt
> +                    var contact: Contact?
Имею в виду привести к более красивому решению

2021-12-12 15:44 UTC, nmodelov commented on app/src/main/java/com/shudss00/android_course/MainActivity.kt
> +private var REQUEST_CODE_READ_CONTACTS = 1
точно var?

2021-12-12 15:44 UTC, nmodelov commented on app/src/main/java/com/shudss00/android_course/MainActivity.kt
> +private var READ_CONTACTS_GRANTED = false
Сделать локальным полем класса. + Капс для констант

2021-12-13 18:27 UTC, s9myon commented on app/src/main/java/com/shudss00/android_course/Contact.kt
> +    val dayOfBirth: Calendar? = null
В каком смысле статичные? То что я их не использую?

2021-12-14 06:00 UTC, nmodelov commented on app/src/main/java/com/shudss00/android_course/Contact.kt
> +    val dayOfBirth: Calendar? = null
Для чего они тебе нужны? если ты хочешь определить значения полей класса по умолчанию, то ты прям в конструкторе можешь указать дефолтное значение

2021-12-15 15:18 UTC, s9myon commented on app/src/main/java/com/shudss00/android_course/Contact.kt
> +    val dayOfBirth: Calendar? = null
Исправил?

2021-12-15 15:18 UTC, s9myon commented on app/src/main/java/com/shudss00/android_course/ContactDetailsFragment.kt
> +                    buttonBirthdayNotify.visibility = View.INVISIBLE
Исправил

2021-12-15 15:19 UTC, s9myon commented on app/src/main/java/com/shudss00/android_course/MainActivity.kt
> +            Toast.makeText(this, "Требуется установить разрешения", Toast.LENGTH_LONG).show()
Исправил

2021-12-15 15:19 UTC, s9myon commented on app/src/main/java/com/shudss00/android_course/MainActivity.kt
>                  .putExtra(MESSAGE, "Today is ${contact.name}'s birthday")
Исправил

2021-12-15 15:19 UTC, s9myon commented on app/src/main/java/com/shudss00/android_course/ContactService.kt
> +                            number = if (numberList.isNotEmpty()) numberList[0] else null
Исправил

2021-12-15 15:20 UTC, s9myon commented on app/src/main/java/com/shudss00/android_course/ContactService.kt
> +                    var birthday: Calendar?
Исправил?

2021-12-15 15:20 UTC, s9myon commented on app/src/main/java/com/shudss00/android_course/ContactService.kt
> +                    var contact: Contact?
Исправил?

2021-12-15 15:20 UTC, s9myon commented on app/src/main/java/com/shudss00/android_course/MainActivity.kt
> +private var REQUEST_CODE_READ_CONTACTS = 1
Исправил

2021-12-15 15:20 UTC, s9myon commented on app/src/main/java/com/shudss00/android_course/MainActivity.kt
> +private var READ_CONTACTS_GRANTED = false
Исправил

2021-12-23 05:38 UTC, merged